// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAswHV0kyyt-p58qqS2YKZkJ8v_W8VyGEw',
    appId: '1:187600160372:web:4c4996b545c7a4977d7321',
    messagingSenderId: '187600160372',
    projectId: 'push-notification-v2-cf040',
    authDomain: 'push-notification-v2-cf040.firebaseapp.com',
    storageBucket: 'push-notification-v2-cf040.firebasestorage.app',
    measurementId: 'G-509N2192GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSW3m568Tf4iDwr9Ebmxnewgv_GY1gIBE',
    appId: '1:187600160372:android:d6abcc89c38232197d7321',
    messagingSenderId: '187600160372',
    projectId: 'push-notification-v2-cf040',
    storageBucket: 'push-notification-v2-cf040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF00zK44ZDyh1NPY6ye_CwYRGQ_2uFKLk',
    appId: '1:187600160372:ios:f8dd914ef93515ca7d7321',
    messagingSenderId: '187600160372',
    projectId: 'push-notification-v2-cf040',
    storageBucket: 'push-notification-v2-cf040.firebasestorage.app',
    iosBundleId: 'com.example.waterLevelMonitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF00zK44ZDyh1NPY6ye_CwYRGQ_2uFKLk',
    appId: '1:187600160372:ios:f8dd914ef93515ca7d7321',
    messagingSenderId: '187600160372',
    projectId: 'push-notification-v2-cf040',
    storageBucket: 'push-notification-v2-cf040.firebasestorage.app',
    iosBundleId: 'com.example.waterLevelMonitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAswHV0kyyt-p58qqS2YKZkJ8v_W8VyGEw',
    appId: '1:187600160372:web:6d059caabe3dcf037d7321',
    messagingSenderId: '187600160372',
    projectId: 'push-notification-v2-cf040',
    authDomain: 'push-notification-v2-cf040.firebaseapp.com',
    storageBucket: 'push-notification-v2-cf040.firebasestorage.app',
    measurementId: 'G-1HTCQS1JJG',
  );
}
